### ISSUE TITLE
Mapping market data subscriptions to exchange ID

### ISSUE THREAD

**Issue by tikidave** [tradovate/api#18]
I am trying to get a list of exchanges a user has access to, and then use those id's to query more information about each exchange.  Currently I am using the `marketDataSubscriptionPlan/list` and `exchange/list` endpoints, but the ID's do not appear to match up.  

Please let me know the right approach; my use case is to only list the products I have access to.

**Comment by mkvalor** [comment]
Not certain what you mean by "access to" in your question.  I believe -- if a user has a funded live account -- he/she can trade any of the exchanges returned by exchange/list endpoint.  The marketDataSubscriptionPLan/list covers only the data feed, and it's not too surprising that the ids for the two of them don't match up, since Tradovate offers bundled subscriptions, etc.  Or a user may get market data from some other provider, but only execute orders on Tradovate using exchanges/list in the code that looks up contracts. 

So, if you want to restrict trading to only those exchanges for which the user has an active data subscription through Tradovate, you may need to do the mapping of the tradable exchanges to the exchanges with market data supplied from the marketDataSubscriptionPlan endpoints yourself.

**Comment by tikidave** [comment]
Makes sense, thanks!
